apiVersion: apps/v1          # Fixed: Correct API version
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app           # Optional: Add labels to metadata
spec:
  replicas: 2                # Number of replicas; adjust as needed
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: myapp
        image: riajul98/my-flask-app:latest  # Use a specific tag
        ports:
        - containerPort: 5000
